### ISSUE TITLE
Is it possible to do this with a VM?

### ISSUE THREAD

**Issue by carboniris** [xomachine/SteamForwarder#1]
Not sure if this is even feasible, but I find that my games sometimes work better in VirtualBox than in Wine. Could this project integrate Windows games in a VM guest with the host's Linux Steam installation?

**Comment by xomachine** [comment]
In theory it is possible to build project that provides such an integration (it could be done via wrapping steam api calls to network packets and passing it through VMs network adapter).

But this project is only provides the wine-specific realization of the wrapper.

**Comment by carboniris** [comment]
I don't have a ton of time to browse the source at the moment, how do Wine
games communicate with Linux Steam under your implementation currently? I
might be able to write a TCP wrapper to accomplish this.

**Comment by xomachine** [comment]
It uses wine native mechanism of making linux side calls from the windows side code, so no network stuff is necessary. More about that can be found [here](https://wiki.winehq.org/Winelib_User's_Guide) and especially [here](https://wiki.winehq.org/Winelib_User%27s_Guide#Building_Winelib_DLLs). Most of the SteamForwarder code is automatically generated routine that just declares a method or a function for windows call conventions and calls the linux-side steam api method inside the implementation. The interesting parts can be only found in [callback related code](https://github.com/xomachine/SteamForwarder/blob/master/callbacks.cpp) and in [method](https://github.com/xomachine/SteamForwarder/blob/f19590fa74dc552245a0aa70d7036d3ac0102a45/autoclass/wrap_isteamfriends.cpp#L35)s that return CSteamID (there is some magic to fit windows call conventions)

**Comment by xomachine** [comment]
Seems like a question a bit outdated and was already answered, so I'm closing it.
