### ISSUE TITLE
Impossible to use with games that statically link steam_api.dll?

### ISSUE THREAD

**Issue by bmwalters** [xomachine/SteamForwarder#11]
Hi there. Thanks for working on this cool project. I'm trying to run a game (appid 32440) which statically links in `steam_api.dll`. If that is the case, it's impossible to use this library then, right? If so, should this be added to the `README`?

**Comment by xomachine** [comment]
I did not even suspect about such a linkage option for steam_api.dll . I've added a notice to the README.
