### ISSUE TITLE
app_install password is visible in command history

### ISSUE THREAD

**Issue by bmwalters** [xomachine/SteamForwarder#12]
Because the password is passed in via a command line argument, it is recorded in the user's shell history. Most applications ask for a password separately using something like [`getpass`](https://docs.python.org/3/library/getpass.html). It also gives the user peace-of-mind because the password isn't cleary visible in the terminal.

**Comment by xomachine** [comment]
Indeed, the password should not be stored in the shell history. Thanks for the tip-off. Fixed by d368eda32863e6f706d81a5e771ec31109186c5a
