### ISSUE TITLE
Failure to build with LTO

### ISSUE THREAD

**Issue by John-Gee** [xomachine/SteamForwarder#15]
As asked on reddit:

When LTO is set in /etc/makepkg.conf the build fails at link.

I'm using the aur package without modification to it.

Full flags:
CPPFLAGS="-D_FORTIFY_SOURCE=2"
CFLAGS="-march=native -O2 -pipe -fstack-protector-strong -fno-plt -fstack-check -flto=$(nproc)"
CXXFLAGS="${CFLAGS}"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-flto"

Failure:

aur-steamforwarder-git/src/SteamForwarder/tools/nimcache/dllparser.o: In function `findBestSOLib_JqYlfcFyaB8KuQo9ckp8G9bA':
dllparser.c:(.text+0xd8c): undefined reference to `contains_HKT6OZnEmHzo1Z3izIwLZQ'
aur-steamforwarder-git/src/SteamForwarder/tools/nimcache/dllparser.o: In function `NimMainModule':
dllparser.c:(.text+0x1bc5): undefined reference to `NTI_O5h9b2DHiZ9as6IlqEXhDAkg_'
dllparser.c:(.text+0x1ff4): undefined reference to `NTI_PACZxzsw3jicSea9ai2ghqw_'
dllparser.c:(.text+0x2011): undefined reference to `initTable_zV5oU6FeS1GaZMwcoDufeg'
dllparser.c:(.text+0x224d): undefined reference to `contains_HKT6OZnEmHzo1Z3izIwLZQ'
dllparser.c:(.text+0x22eb): undefined reference to `X5BX5Deq__B8MciEVBahlJqgunXtrlVg'
dllparser.c:(.text+0x263e): undefined reference to `contains_Oi9bcvMPJyGzGx7X1KepzhA'
dllparser.c:(.text+0x2664): undefined reference to `NTI_pfrdooyxJsC6cg34ebuBag_'
dllparser.c:(.text+0x26a4): undefined reference to `X5BX5D__reB9awySmHmXRCQNcbeZdSA'
aur-steamforwarder-git/src/SteamForwarder/tools/nimcache/stdlib_system.o: In function `systemDatInit000':
stdlib_system.c:(.text+0x22a9d): undefined reference to `NTI_Ryg5db24dBRIzTUa2BQTPg_'
aur-steamforwarder-git/src/SteamForwarder/tools/nimcache/spec.o: In function `readSpecFile_n9aGpRsAchlau7r235IRJGA':
spec.c:(.text+0x185): undefined reference to `NTI_O5h9b2DHiZ9as6IlqEXhDAkg_'
spec.c:(.text+0x1a1): undefined reference to `initOrderedTable_Pa27xKKJzIWadP7w7QXP8Q'
spec.c:(.text+0x3dd): undefined reference to `X5BX5Deq__MFsEny7JeInf7luyFRIddw'
aur-steamforwarder-git/src/SteamForwarder/tools/nimcache/spec.o: In function `unknown_specDatInit000':
spec.c:(.text+0x4b5): undefined reference to `NTI_hLlQjbV9bLNq5PFxYcqacsA_'
aur-steamforwarder-git/src/SteamForwarder/tools/dllparser: hidden symbol `initOrderedTable_Pa27xKKJzIWadP7w7QXP8Q' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

It builds fine if I remove "-flto=$(nproc)" from CFLAGS, but simply adding it without the correct LDFLAGS would probably not do much.

(It's not that I need LTO on to build this, it's just annoying to have to turn it off either in makepkg.conf or in the pkgbuild :) )

**Comment by xomachine** [comment]
Can not reproduce even with manualy passed -flto options to the underlying gcc compiler. Can you try to compile with modified tools/Makefile [with this patch](https://gist.github.com/xomachine/5d8717e2a2908994019aee6fc3150fe8)

Then send the full compilation output.

**Comment by John-Gee** [comment]
There:

https://gist.github.com/John-Gee/db7b68c1ab2722c0d7ba97363eb36b7d

**Comment by xomachine** [comment]
Well, it looks strange. As I suspected, the `-flto` option is not being passed to gcc compiler nor linker, but the error persist.

For further investigation I would like to look at the gcc compiler version and the (archived) content of the `tools/nimcache` directory to check if the generated C code and object files differ from my ones.

**Comment by John-Gee** [comment]
gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin//gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.3.0 (GCC)

standard Arch (testing) package.


[nimcache.zip](https://github.com/xomachine/SteamForwarder/files/1694502/nimcache.zip)

**Comment by xomachine** [comment]
Your nimcache does not compile indeed. So it is a Nim issue. Try to update your Nim compiler (it is older than my)

**Comment by John-Gee** [comment]
I just compiled nim and it's the same.

It may very well be an nim issue, if so feel free to close this.

Thank you!

**Comment by xomachine** [comment]
The cache you've sent is not compiling in both of cases: with and without `-flto`. It shows many syntax errors in `stdlib_system.c`. (Looks like the end of file is filled with garbage). Please tell me which version of Nim compiler you have used last time.

**Comment by John-Gee** [comment]
My previous one was 20180204-1 compiled around 9PM PST on the 3rd.
Without LTO it did compile fine, but maybe it changes nimcache whether I set it or not.

**Comment by xomachine** [comment]
The `nim -v` command shows more informative output. For example:
``` bash
$ nim -v
Nim Compiler Version 0.17.3 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b4eff82e62883d307db83f3e875be2e1b521b0ff
active boot switches: -d:release -d:nativeStackTrace

```
I want to install the version from exact commit and test it.

**Comment by John-Gee** [comment]
Well my current one is:

nim -v
zsh: correct 'nim' to 'nm' [nyae]? n
Nim Compiler Version 0.17.3 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: e2cf3b94f22f9d028500a3b8628c3cd0b381d65f
active boot switches: -d:release -d:nativeStackTrace

actually it does not compile at all with that one :/

Back to the previous one which works without LTO:
nim -v                
Nim Compiler Version 0.17.3 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b4eff82e62883d307db83f3e875be2e1b521b0ff
active boot switches: -d:release -d:nativeStackTrac

**Comment by xomachine** [comment]
Very interesting situation. Both of versions works for me flawlessly. But there is still [a big difference](https://gist.github.com/xomachine/21dc1b55b774fbda75e9f184b855858d) between the nimcache you sent and the nimcache I obtained during compilation.

Is it possible that you are using non-default `/etc/nim.cfg` ?

**Comment by John-Gee** [comment]
I used the standard one that came with nim-git, nothing else.

**Comment by xomachine** [comment]
I figured out what the problem it was. Nim does not support two or more compiler invocations in the same directory, but make tries to build tasks in parallel. So the nimcaches was being overlapped and overwritten that caused the error at link stage and more wondering things.

I've disabled parallel build in the PKGBUILD in AUR (Nim compiler builds things in parallel anyway) and now the problem must be fixed. Please reopen this issue if it is not.

**Comment by John-Gee** [comment]
That seems to have worked indeed!
Good finding!

(and it also builds again with latest nim, not sure if you fixed something or nim did for that but I thought I'd mention it).

Thank you!
John
