### ISSUE TITLE
steamnative: local variable 'curlang' referenced before assignment

### ISSUE THREAD

**Issue by toofar** [xomachine/SteamForwarder#19]
I got the following error when trying to download a game (Divinity II 219780) via --steamnative

    Traceback (most recent call last):
      File "./sf_install", line 211, in <module>
        appinfos = steaminterface.getAppInfo()
      File "/home/user/projects/SteamForwarder/installer/steam.py", line 92, in getAppInfo
        self.appinfo = parse_app_info(answer, self.appid)
      File "/home/user/projects/SteamForwarder/installer/steaminterface.py", line 106, in parse_app_info
        appinfos['regfile'] = makeRegFile(installactions['Registry'], curlang)
    UnboundLocalError: local variable 'curlang' referenced before assignment

I "fixed" it by adding a default `curlang = "english"` just above the `if 'baselanguages' in appinfo['depots']:`. 

I'm not sure if this is a change in steam's appinfo format or just for this game but here is the json from the console:

    {
    	"common"
    	{
    		"name"		"Divinity II: Developer's Cut"
    		"type"		"Game"
    		"clienticon"		"c3fa656adf90d83643e4a912554f66a72a632d9a"
    		"clienttga"		"543dab2aa5001768d54ff31e836b9c31cf848191"
    		"icon"		"e0dae7e1b381620b7265023f350b169990da1abf"
    		"logo"		"4f27f30ba5b89a80f162072e824d2255752945ad"
    		"logo_small"		"4f27f30ba5b89a80f162072e824d2255752945ad_thumb"
    		"metacritic_name"		"Divinity 2: Developer's Cut"
    		"small_capsule"
    		{
    			"english"		"capsule_231x87.jpg"
    		}
    		"header_image"
    		{
    			"english"		"header.jpg"
    		}
    		"community_hub_visible"		"1"
    		"gameid"		"219780"
    		"store_tags"
    		{
    			"0"		"122"
    			"1"		"1684"
    			"2"		"1695"
    			"3"		"4046"
    			"4"		"1697"
    			"5"		"4231"
    			"6"		"21"
    			"7"		"19"
    			"8"		"4182"
    			"9"		"4057"
    			"10"		"4166"
    			"11"		"4747"
    			"12"		"1719"
    			"13"		"4172"
    			"14"		"1756"
    			"15"		"7208"
    			"16"		"4136"
    			"17"		"1742"
    		}
    	}
    	"extended"
    	{
    		"developer"		"Larian Studios"
    		"gamedir"		"Divinity 2 Director's Cut"
    		"homepage"		"http://www.larian.com"
    		"icon"		""
    		"noservers"		"0"
    		"sourcegame"		"1"
    		"state"		"eStateAvailable"
    		"thirdpartycdkey"		"1"
    		"visibleonlywhensubscribed"		"1"
    		"publisher"		"Larian Studios"
    		"gamemanualurl"		"http://store.steampowered.com/manual/219780/"
    	}
    	"config"
    	{
    		"contenttype"		"3"
    		"installdir"		"divinity2_dev_cut"
    		"launch"
    		{
    			"0"
    			{
    				"executable"		"Autorun.exe"
    				"config"
    				{
    					"oslist"		"windows"
    				}
    			}
    		}
    		"installscriptsignature"		"344175d13c643b23acf9fa9a7c9c100b6b711955bbbcd9fd670dc754f95efc36ccc8e528fe34cd1382bb2ca9af8dde688312d2ab5ba96f9c3666aa9d08953c22477ae794c1c419c4e729537e616f3ce861ec14e1473069e7e9b56be43fafd49ccccb1029bd724770074ea3c83b3c93faf4ebb653e19aca837d003f406a506d93"
    		"installscriptoverride"		"1"
    	}
    	"install"
    	{
    		"Registry"
    		{
    			"hkey_current_user\\software\\larian studios\\divinity ii - dks"
    			{
    				"string"
    				{
    					"target_folder"		"%INSTALLDIR%"
    				}
    			}
    		}
    		"run process"
    		{
    			"directx"
    			{
    				"hasrunkey"		"HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\219780"
    				"process 1"		"%INSTALLDIR%\\support\\DirectX\\Feb2007\\DXSETUP.exe"
    				"command 1"		"/silent"
    				"nocleanup"		"1"
    			}
    			"vcredist"
    			{
    				"hasrunkey"		"HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\219780"
    				"process 1"		"%INSTALLDIR%\\support\\VCRedist\\VS80sp1-redist_x86-4053.exe"
    				"command 1"		"/q"
    				"nocleanup"		"1"
    			}
    			"vcredist2"
    			{
    				"hasrunkey"		"HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\219780"
    				"process 1"		"%INSTALLDIR%\\support\\VCRedist\\VS90sp1-redist_x86-9.0.30729.17.exe"
    				"command 1"		"/q"
    				"nocleanup"		"1"
    			}
    			"physx"
    			{
    				"hasrunkey"		"HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\219780"
    				"process 1"		"%INSTALLDIR%\\support\\PhysX\\PhysX_9.09.0428_SystemSoftware.exe"
    				"command 1"		"/quiet"
    				"nocleanup"		"1"
    			}
    		}
    	}
    	"depots"
    	{
    		"219781"
    		{
    			"name"		"Divinity 2: Developer's Cut Content"
    			"systemdefined"		"1"
    			"config"
    			{
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"680918273947975519"
    			}
    			"maxsize"		"3051386981"
    		}
    		"219782"
    		{
    			"name"		"English"
    			"config"
    			{
    				"language"		"english"
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"6253915778589161688"
    			}
    			"maxsize"		"6758992006"
    		}
    		"219783"
    		{
    			"name"		"French"
    			"config"
    			{
    				"language"		"french"
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"7129837099643880910"
    			}
    			"maxsize"		"7544423299"
    		}
    		"219784"
    		{
    			"name"		"German"
    			"config"
    			{
    				"language"		"german"
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"8969967851637397177"
    			}
    			"maxsize"		"7410703885"
    		}
    		"219785"
    		{
    			"name"		"Russian"
    			"config"
    			{
    				"language"		"russian"
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"2894376249660804045"
    			}
    			"maxsize"		"7527235358"
    		}
    		"219786"
    		{
    			"name"		"Polish"
    			"config"
    			{
    				"language"		"polish"
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"2196818784475338260"
    			}
    			"maxsize"		"7711172530"
    		}
    		"219787"
    		{
    			"name"		"Anthology"
    			"config"
    			{
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"5709788403628094774"
    			}
    			"maxsize"		"209482781"
    		}
    		"219788"
    		{
    			"name"		"Italian"
    			"config"
    			{
    				"language"		"italian"
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"7151150613532782803"
    			}
    			"maxsize"		"6758992006"
    		}
    		"219789"
    		{
    			"name"		"Spanish"
    			"config"
    			{
    				"language"		"spanish"
    				"oslist"		"windows"
    			}
    			"manifests"
    			{
    				"public"		"6918006692494886749"
    			}
    			"maxsize"		"6758992006"
    		}
    		"overridescddb"		"1"
    		"preloadonly"		"1"
    		"branches"
    		{
    			"public"
    			{
    				"buildid"		"23566"
    			}
    		}
    	}
    	"ufs"
    	{
    		"quota"		"1000000000"
    		"maxnumfiles"		"1000"
    		"savefiles"
    		{
    			"0"
    			{
    				"root"		"WinAppDataLocal"
    				"path"		"Divinity 2/Savegames"
    				"pattern"		"*.dxg"
    				"platforms"
    				{
    					"1"		"Windows"
    				}
    				"recursive"		"1"
    			}
    		}
    	}
    }

**Comment by xomachine** [comment]
The `curlang` value should not have any influence on registry key creation if there is no `baselanguages`. At least in theory.  So I left the empty value.

Thank you for the report!
