### ISSUE TITLE
question about 64bit steam api(steam_api64.dll)

### ISSUE THREAD

**Issue by cheesehead544** [xomachine/SteamForwarder#20]
is steamforwarder able to work with 64 bit steam api?

**Comment by xomachine** [comment]
The `steam_api64.dll.so` implementation is under heavy development. Now I'm trying to find a way to avoid the Nim runtime and the game memory overlap.

**Comment by l33tlinuxh4x0r** [comment]
I was able to get it working by copying the steam_api64.dll to steam_api.dll However the script should account for this and make the wine arch 64bit but it doesn't. I had to edit the Launcher.sh Also the Launcher.sh needs executable permissions which it doesn't have by default.

**Comment by xomachine** [comment]
The installer script was not even changed to support 64-bit installation. In a first place I'm trying to get working the library itself.
Unfortunately, now I have not enough time for active development.

**Comment by xomachine** [comment]
The commit https://github.com/xomachine/SteamForwarder/commit/af3d092abd85fdab509bab79a84b1cddda6a61d6 has introduced 64-bit support for the installer script.

The library itself may work, but probably won't. The only game that I was able to run with this implementation is [Ride Demo](https://steamdb.info/app/355660/).

**Comment by xomachine** [comment]
`steam_api64.dll` is fully supported since e765948c2066cb38eff92ce03f6f6ac0485ff00a (in the devel branch at the moment of posting)
Tested in [Realm Royale](https://store.steampowered.com/app/813820/Realm_Royale/).
