### ISSUE TITLE
LD_PRELOAD / ELFCLASS error with gameoverlayrenderer.so

### ISSUE THREAD

**Issue by r2rX** [xomachine/SteamForwarder#3]
Hey there,

Just wanted to report a bug that i'm experiencing. I'm currently using Ubuntu 16.10 x64 and after setting up a game, I attempt to run the Launch.sh script. When I do, WINE temporarily opens but closes with the following error:

```
./Launch.sh 
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```
Steam is opened prior to running the launcher. Let me know if there's any more info you require.

**Comment by xomachine** [comment]
> ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

This error is harmless.
The problem you encountered might be in your WINEPREFIX. The launch script sets the WINEARCH environment variable to win32. So If you're using 64-bit prefix, wine won't start. Just try to remove
`export WINEARCH=win32` from the launch script or use 32-bit WINEPREFIX. If the problem still present, please, post here the lastrun.log file from the launch script location.

**Comment by r2rX** [comment]
Hey,

The WINE prefix is 32bit. Here's the log info you requested:

```
 ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
fixme:winediag:start_process Wine Staging 2.2 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x3c27f0, 0x3d0030, 0x3d0048) stub.
fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x3c2560, 43) stub
```

**Comment by xomachine** [comment]
Looks like the game does not even tries to communicate with the library.
What game you're trying to launch? Does this game start with the windows steam on wine?
It would be good to look at the launch script also.
Another things that could help to figure out the problem is:
* deleting the `steam_api.dll` from the game folder (it should not cause any new error messages)
* setting `*steam_api` to builtin or disabled in winecfg ("disabled" should cause an error. If it isn't - the `steam_api.dll` loads somehow dynamically and can not be redirected by wine. In this case I can not do anything with that.)

**Comment by r2rX** [comment]
I'm trying to launch Grim Dawn; which i've gotten running successfully through Steam via Wine.

From testing, I get the same identical log result whether I delete the steam_api.dll, set is as builtin or disabled in Wines library manager.

Here's the content from the Launch script:


```
#!/bin/bash
export WINEPREFIX="/home/xx/.wine"
export WINEDLLPATH+=":/home/xx/Applications/SteamForwarder"
export LD_LIBRARY_PATH+=":/home/xx/.local/share/Steam/ubuntu12_32/:/home/xx/Applications/SteamForwarder"
export WINEDEBUG="trace+steam_api"
export WINEARCH="win32"
export WINEDLLOVERRIDES="*steam_api=b"
export SteamAppId="219990"
export SteamControllerAppId="219990"
export SteamGameId="219990"
export SteamUser="anonymous"
export SteamAppUser="anonymous"
LD_PRELOAD="gameoverlayrenderer.so" wine "/home/xx/.local/share/Steam/steamapps/common/Grim Dawn/grim dawn.exe"  &> "$(dirname "$0")/lastrun.log"
```

**Comment by xomachine** [comment]
It looks like this game is DRM protected. So it means that the game checks steam process in memory before accessing steam_api.dll. I have no solution for this case and not even sure that any solution to handle DRM-related stuff is legal.

**Comment by r2rX** [comment]
Thanks for the feedback. It's a little disappointing (not in you, of course :) ) but it makes sense. I'll close this issue. Cheers.
