### ISSUE TITLE
Downloads in root

### ISSUE THREAD

**Issue by DerRehberg** [xomachine/SteamForwarder#5]
Quite funny.
Looked for an hour, why he can't find the game.
Turns out he downloaded it inside the root folder.
On Arch here.

**Comment by craftyguy** [comment]
in / or /root ? Are you running steam as root?

**Comment by xomachine** [comment]
The download location is set by default to `$HOME/.local/share/Steam/steamapps`. You can override the location by the `-s` key of `app_install.py`.
