### ISSUE TITLE
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

### ISSUE THREAD

**Issue by aslhdyt** [xomachine/SteamForwarder#9]
hello,
i successfully download the game. when i try to run the via .sh script i get this:

lastrun.log
```
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

any ideas?
thanks

**Comment by xomachine** [comment]
Those messages are harmless. Could you provide more detailed description of problem? What version of wine you are using? What game you are trying to start and what exactly happens next?
Also, it might be useful to see the generated .sh script to check for possible mistakes.

**Comment by aslhdyt** [comment]
version wine-1.6.2

wine prefix 64bit

generated .sh script
```
#!/bin/bash
export WINEPREFIX="/home/assel/.wine"
export WINEDLLPATH+=":/home/assel/SteamForwarder"
export LD_LIBRARY_PATH+=":/home/assel/.local/share/Steam/ubuntu12_32/:/home/assel/SteamForwarder"
export WINEDEBUG="trace+steam_api"
export WINEARCH="win64"
export WINEDLLOVERRIDES="*steam_api=b"
export SteamAppId="554620"
export SteamControllerAppId="554620"
export SteamGameId="554620"
export SteamUser="SENSOR"
export SteamAppUser="SENSOR"
LD_PRELOAD="gameoverlayrenderer.so" wine "/home/assel/.local/share/Steam/steamapps/common/Life is Strange - Before the Storm/Life is Strange - Before the Storm.exe"  &> "$(dirname "$0")/lastrun.log"
```

trying to start Life is Strange - Before the Storm. 
[steam store](http://store.steampowered.com/app/554620/Life_is_Strange_Before_the_Storm/)

nothing is running when run the script..
```
assel@assel-linuxmint ~/.local/share/Steam/steamapps/common/Life is Strange - Before the Storm $ ./Life\ is\ Strange:\ Before\ the\ Storm.sh
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
assel@assel-linuxmint ~/.local/share/Steam/steamapps/common/Life is Strange - Before the Storm $ 

```

ps:
i run [Life is Strange ](http://store.steampowered.com/app/319630/Life_is_Strange__Episode_1/) cracked without steam flawlessly,
which has no big difference with the game im trying to run, in terms of  graphic and hardware requirement

**Comment by xomachine** [comment]
As I can see, there are no attempts to access the steam api from the game, so the game stops before SteamForwarder begin doing its job.
There might be two reasons why the game can not start.
1) The game executable is for 64bit system and steam api which is not supported by SteamForwarder
2) The game is protected by DRM and trying to find steam as windows process which obviously does not exist.

**Comment by aslhdyt** [comment]
no solution then?

thanks for the explanation..
